[[repos]]
repo = "builtin"
hooks = [
  {id = "check-added-large-files", args = ["--maxkb=80"], exclude = '^uv\.lock$'},
  {id = "check-case-conflict"},
  {id = "check-executables-have-shebangs"},
  {id = "check-illegal-windows-names"},
  {id = "check-merge-conflict"},
  {id = "check-shebang-scripts-are-executable"},
  {id = "check-toml"},
  {id = "check-yaml"},
  {id = "end-of-file-fixer"},
  {id = "file-contents-sorter", files = '^(\.github/CODEOWNERS|\.gitignore)$'},
  {id = "trailing-whitespace"}
]

[[repos]]
repo = "https://github.com/abravalheri/validate-pyproject"
rev = "v0.25"
hooks = [{id = "validate-pyproject"}]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.22"
hooks = [{id = "ruff-check"}]

[[repos]]
repo = "https://github.com/astral-sh/ty-pre-commit"
rev = "v0.0.60"
hooks = [{id = "ty", args = ["--isolated", "--no-python-downloads"]}]

[[repos]]
repo = "https://github.com/Yelp/detect-secrets"
rev = "v1.5.0"
hooks = [{id = "detect-secrets", args = ["--baseline", ".secrets.baseline"]}]
