[[repos]]
repo = "builtin"
hooks = [
  {id = "check-added-large-files", args = ["--maxkb=50", "--enforce-all"], exclude = '^uv\.lock$'},
  {id = "check-case-conflict"}, {id = "check-executables-have-shebangs"}, {id = "check-illegal-windows-names"},
  {id = "check-merge-conflict"}, {id = "check-shebang-scripts-are-executable"}, {id = "check-toml"},
  {id = "check-yaml"}, {id = "end-of-file-fixer"}, {id = "trailing-whitespace"},
  {id = "file-contents-sorter", files = '^\.(github/CODEOWNERS|.*ignore)$'}
]

[[repos]]
repo = "https://github.com/abravalheri/validate-pyproject"
rev = "0.26"
hooks = [{id = "validate-pyproject"}]

[[repos]]
repo = "https://github.com/betterleaks/betterleaks"
rev = "v1.8.1"
hooks = [{id = "betterleaks"}]

[[repos]]
repo = "https://github.com/jonathandung/check-empty"
rev = "v1.2.1"
hooks = [{id = "check-empty", files = '^pygensuggestions/py\.typed$'}]
