from ._types import Candidates
from typing import AnyStr, Final, Literal
__all__ = 'MAX_CANDIDATE_ITEMS', 'MAX_STRING_SIZE', 'lev_dist', 'sub_cost', 'suggest'
MAX_STRING_SIZE: Final = 40
MAX_CANDIDATE_ITEMS: Final = 750
def lev_dist(s: AnyStr, t: AnyStr, n: int, /) -> int: ...
def sub_cost(s: AnyStr, t: AnyStr, /) -> Literal[0, 1, 2]: ...
def suggest(candidates: Candidates[AnyStr], item: AnyStr, /) -> AnyStr|None: ...