from _collections_abc import MutableSequence
from typing import Final, Literal
MAX_STRING_SIZE: Final[int]
MAX_CANDIDATE_ITEMS: Final[int]
def lev_dist(s: str, t: str, M: int, b: MutableSequence[int], /) -> int: ...
def sub_cost(s: str, t: str, /) -> Literal[0, 1, 2]: ...
def suggest(opts: list[str], name: str, /) -> str|None: ...