name: Upload Python Package
on:
  release:
    types: [published]
permissions:
  contents: read
jobs:
  release-build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/pygensuggestions/${{github.event.release.name}}
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-python@v6.2.0
        with:
          python-version: 3.14
      - name: Build release distributions
        run: |
          pip install -U pip .[dev]
          python -m build
          twine upload dist/* --verbose
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{secrets.PYPI_TOKEN}}
