name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.2
    - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
    - run: uvx ruff check --output-format=github
    - run: uvx ty check --output-format=github
    - run: COVERAGE_RCFILE=.coveragerc uv run --with ".[test]" --python 3.15 -m pytest -vv --cov-report xml
    - run: uv run --with ".[test]" --python 3.8 -m pytest -vv
    - run: uv run --with ".[test]" --python pp38 -m pytest -vv --no-cov
    - run: uv run --with ".[test]" --python gp311 -m pytest -vv --no-cov
