name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.2
    - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      with:
        python-version: "3.9"
        cache-python: true
        activate-environment: true
    - run: uvx ruff check --output-format=github && uvx ty check --output-format=github
    - run: COVERAGE_RCFILE=.coveragerc uv run --with ".[test]" pytest -vv